apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria-consumer
  namespace: saude-auditoria-gateway
  labels:
    app: auditoria-consumer
    component: consumer
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auditoria-consumer
  template:
    metadata:
      labels:
        app: auditoria-consumer
        component: consumer
        tier: backend
      annotations:
        argocd-image-version: "2026-01-07T00:19:21Z"
    spec:
      containers:
        - name: consumer
          image: 961341521437.dkr.ecr.sa-east-1.amazonaws.com/saude-auditoria-consumer:20260110155340
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "kafka-0.kafka-headless.saude-auditoria-gateway.svc.cluster.local:9092,kafka-1.kafka-headless.saude-auditoria-gateway.svc.cluster.local:9092,kafka-2.kafka-headless.saude-auditoria-gateway.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "saude.auditoria.login"
            - name: KAFKA_GROUP
              value: "auditoria-consumers"
            - name: CLICKHOUSE_HOST
              value: "clickhouse.saude-auditoria-gateway.svc.cluster.local"
            - name: CLICKHOUSE_PORT
              value: "9000"
            - name: CLICKHOUSE_DATABASE
              value: "auditoria"
            - name: REDIS_HOST
              value: "redis.saude-auditoria-gateway.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_TTL
              value: "300"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
