apiVersion: v1
data:
  PI_DIGITAL_API_URL: "https://pidigital.pi.gov.br/api/assinatura-ws/assinatura"
  PI_KEYCLOAK_URL: "https://login.pi.gov.br"
  PI_CLIENT_SECRET: "6u5fXN5O4HiK7j0e2uvMkdpYMkeYx3FB"
  PI_LOGIN_SITE_URL: "https://login.pi.gov.br"
  X_API_KEY_CONNECT: "spHtzp9vrWHZFeToecKX53ytW6wEDCoWZ4tO6tRG3OmVFdJDLifngeY5vwHq122D" 
  RAILS_ENV: production
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  DATABASE_POOL: "8"
  SENTRY_URL: "https://5acf738d9d6b3451cdb7eac1064e7b3a@sentry.bigdatasys.net/10"
  APP_HOST: "cuidarpi-floriano.bigdatasys.net"
  BUNDLE_JOBS: "4"
  BUNDLE_RETRY: "3"
  DATABASE_DEV: tenant_cuidar_floriano_db
  DATABASE_HOST: dev-db-cuidar-new2.postgres.database.azure.com
  DATABASE_PASSWORD: nt1L2e0AFiRn6FREfYf9hXUWcO3gsOTs
  DATABASE_PORT: "6432"
  DATABASE_PROD: tenant_cuidar_floriano_db
  DATABASE_TEST: tenant_cuidar_floriano_db  
  PGWEB_DATABASE_URL: postgres://postgres@db-3/tenant_cuidar_floriano_db?sslmode=disable
  SECRET_KEY_BASE: 8c4d9f264ea397f4767e4fc24a68a95b88d0787048711fc841e65bb33cd1e64500be8140751470177dbf55842f267b52f9e2f744e43692ee16efe57b99860580
  RAILS_MAX_THREADS: "5"
  WEB_CONCURRENCY: "2"
  SIDEKIQ_CONCURRENCY: "2"
  HYDRA_HOST: "https://regulapiaui.sesapi.pi.gov.br"
  HIDRA_TOKEN: "d64VPsGZw5XQYMJ9bACZUgtt"
  DATABASE_BI_SESAPI: ""
  # Redis Optimizations
  REDIS_MAXMEMORY_POLICY: "allkeys-lfu"
  REDIS_TIMEOUT: "1"
  # Rails Cache Optimizations  
  RAILS_ACTION_CACHE: "true"
  RAILS_FRAGMENT_CACHE: "true"
  RAILS_CACHE_STORE: "configured"
  RAILS_CACHE_EXPIRES_IN: "configured"
  RAILS_DESKTOP_CACHE_TTL: "configured"
  # Database Optimizations
  DATABASE_INCLUDES_CACHE: "enabled"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: pgweb-env
  name: env
