apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raimundononato-ingress
  namespace: cuidar-raimundononato
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/load-balance: "least_conn"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cuidarpi-raimundononato.bigdatasys.net
      secretName: raimundononato-tls
  rules:
    - host: cuidarpi-raimundononato.bigdatasys.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: raimundononato-service
                port:
                  number: 80