apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
  namespace: saude-auditoria-gateway
data:
  bucket: "<defina-o-nome-do-bucket>"
  # opcional: endpoint vazio usa AWS oficial; preencha se usar VPC endpoint customizado
  endpoint: ""
