apiVersion: v1
data:  
  X_API_KEY_CONNECT: "11jdSUjKYz6J24QmFA6bS1KV9V3LJGXI9c4MUnbwnJPX59P7LnVH4dwAaga0HPQp"
  RAILS_ENV: production
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  DATABASE_POOL: "20"
  SENTRY_URL: "https://28e496976b758934ea545f3f61193e28@sentry.bigdatasys.net/26"
  APP_HOST: "apresentacao.bigdatasys.net"
  BUNDLE_JOBS: "4"
  BUNDLE_RETRY: "3"
  DATABASE_DEV: cuidadodb
  DATABASE_HOST: "dev-db-cuidar-new2.postgres.database.azure.com"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "nt1L2e0AFiRn6FREfYf9hXUWcO3gsOTs"
  DATABASE_PORT: "5432"
  DATABASE_PROD: cuidadodb
  DATABASE_TEST: cuidadodb  
  PGWEB_DATABASE_URL: postgres://postgres@db-3/tenant_apresentacao_db?sslmode=disable
  SECRET_KEY_BASE: 8c4d9f264ea397f4767e4fc24a68a95b88d0787048711fc841e65bb33cd1e64500be8140751470177dbf55842f267b52f9e2f744e43692ee16efe57b99860580
  RAILS_MAX_THREADS: "8"
  WEB_CONCURRENCY: "2"
  SIDEKIQ_CONCURRENCY: "2"
  HYDRA_HOST: "https://regulapiaui.sesapi.pi.gov.br"
  HIDRA_TOKEN: "d64VPsGZw5XQYMJ9bACZUgtt"
  DATABASE_BI_SESAPI: ""
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: pgweb-env
  name: env
