apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: srnhomolog
  name: srnhomolog
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: srnhomolog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 180
  template:
    metadata:
      labels:
        io.kompose.service: srnhomolog
    spec:
      containers:
        - name: srnhomolog
          image: 961341521437.dkr.ecr.sa-east-1.amazonaws.com/saude-publica-web:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              mkdir -p app/public/prd/sia
              mkdir -p app/tmp/pids
              mkdir -p app/tmp/sockets
              # Inicializar rbenv
              source /etc/profile.d/rbenv.sh
              bundle exec rake db:migrate
              bundle exec puma -C config/puma/production.rb
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: azurefile
              mountPath: /mnt/compartilhado
          envFrom:
            - configMapRef:
                name: env
          resources:
            requests:
              cpu: "400m"
              memory: "4Gi"
            limits:
              cpu: "900m"
              memory: "5Gi"
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: azurefile-pvc
      restartPolicy: Always

