apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saude-central-de-notificacao-ingress
  namespace: saude-central-de-notificacao
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "saude-central-de-notificacao-service"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$binary_remote_addr"
spec:
  tls:
    - hosts:
        - notificacao.bigdatasys.net
      secretName: saude-central-de-notificacao-tls
  rules:
    - host: notificacao.bigdatasys.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saude-central-de-notificacao-service
                port:
                  number: 80