apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning-ingress
  namespace:  saude-learning
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - saude-lrn.bigdatasys.net
      secretName: learning-tls
  rules:
    - host: saude-lrn.bigdatasys.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: learning-service
                port:
                  number: 80