apiVersion: v1
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  DATABASE_POOL: "20"
  SENTRY_URL: "https://11b50674bb1c6fd8c409352cc70967f3@sentry.bigdatasys.net/5"
  APP_HOST: isac-homolog.bigdatasys.net
  BUNDLE_JOBS: "4"
  BUNDLE_RETRY: "3"
  DATABASE_DEV: saude_homolog_tenant_isac_db
  DATABASE_HOST: dev-db-cuidar-new2.postgres.database.azure.com
  DATABASE_PASSWORD: nt1L2e0AFiRn6FREfYf9hXUWcO3gsOTs
  DATABASE_PORT: "6432"
  DATABASE_PROD: saude_homolog_tenant_isac_db
  DATABASE_TEST: saude_homolog_tenant_isac_db
  SECRET_KEY_BASE: 8c4d9f264ea397f4767e4fc24a68a95b88d0787048711fc841e65bb33cd1e64500be8140751470177dbf55842f267b52f9e2f744e43692ee16efe57b99860580
  RAILS_MAX_THREADS: "8"
  WEB_CONCURRENCY: "2"
  SIDEKIQ_CONCURRENCY: "8"
  HYDRA_HOST: "https://regulahm.saude.pi.gov.br"
  HIDRA_TOKEN: "882ILCri93gsJpQvzgUbTQtt"
  DATABASE_BI_SESAPI: "data_smart"  
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: pgweb-env
  name: env
