apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-agent-ingress
  namespace: saude-publica
  labels:
    app: saude-event-agent
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - event-agent.bigdatasys.net
      secretName: saude-event-agent-tls
  rules:
    - host: event-agent.bigdatasys.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saude-event-agent-service
                port:
                  number: 80